CC = g++

COMPILER_FLAGS = -std=c++11 -w -O3 -DNDEBUG -Wall -Werror -Wextra -pedantic

LINKER_FLAGS = -lSDL2 -lGL -lGLEW -lSOIL #-lGLU

HELLO = hello.cpp
SHADER = shader.cpp
TEXTURE = texture.cpp
TRANSFORMATION = transformation.cpp

EXECUTABLE_HELLO = hello
EXECUTABLE_SHADER = shader
EXECUTABLE_TEXTURE = texture
EXECUTABLE_TRANSFORMATION = transformation
EXECUTABLES = $(EXECUTABLE_HELLO) $(EXECUTABLE_SHADER) $(EXECUTABLE_TEXTURE) $(EXECUTABLE_TRANSFORMATION)

all: hello shader texture transformation

hello: $(HELLO)
	$(CC) $(HELLO) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(EXECUTABLE_HELLO)

shader: $(SHADER)
	$(CC) $(SHADER) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(EXECUTABLE_SHADER)

texture: $(TEXTURE)
	$(CC) $(TEXTURE) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(EXECUTABLE_TEXTURE)

transformation: $(TRANSFORMATION)
	$(CC) $(TRANSFORMATION) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(EXECUTABLE_TRANSFORMATION)

clean:
	rm *.o *.exe $(EXECUTABLES)

